### ISSUE TITLE
EOF exception while recording D365 Fno using the bzm-correlation recorder template

### ISSUE THREAD

**Issue by StraySquid760** [Blazemeter/CorrelationRecorder#60]
I am getting below EOF exception while recording D365 Fno Application using the BZM correlation recorder template.

java.io.EOFException at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:279) at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:269) at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:175) at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) at org.apache.jmeter.protocol.http.sampler.hc.LaxGZIPInputStream.<init>(LaxGZIPInputStream.java:42) at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.lambda$static$0(HTTPHC4Impl.java:205) at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51) at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:63) at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.readResponse(HTTPSamplerBase.java:1950) at org.apache.jmeter.protocol.http.sampler.HTTPAbstractImpl.readResponse(HTTPAbstractImpl.java:475) at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:678) at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:66) at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1311) at org.apache.jmeter.protocol.http.proxy.Proxy.run(Proxy.java:251) at com.blazemeter.jmeter.correlation.core.proxy.CorrelationProxy.run(CorrelationProxy.java:57)

Let us know in which versions of these tools the error occurs:

- JMeter: 5.6.3
- Correlation Recorder: BZM-Correlation-Recorder Plugin: 2.2.1
- Plugin Manager (if applicable) : 1.0
- Protocol version (if apply, eg: Siebel CRM IP17 & IP18)

**To Reproduce**

Steps to reproduce the bug:

1. Click on BZM-Correlation-Recorder  template and click start 
2. Go to firefox and launch D365 F&O url.

**Comment by diego-ferrand** [comment]
Hey @StraySquid760 it looks like jmeter has issues recording D365 F&O traffic, there are some good suggestions posted in [this blog](https://community.dynamics.com/blogs/post/?postid=42ec2e60-59b4-ee11-92bd-002248511ab4).

There is a section there that indicates a similar issues to what you are facing, and they recommend to set the HTTP Sampler settings type to Java.

If you are still facing the issue, try recording with native jmeter recorder and see if you are facing the same issues. It looks like it might be more in jmeter side than the plugin.

**Comment by StraySquid760** [comment]
Thanks @diego-ferrand . Will try

**Comment by gamorin** [comment]
I will close this issue. @StraySquid760, please if you continue having problems with this, open a new ticket.
